name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Check environment
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
